image: sphinxdoc/sphinx  

pages:
  stage: deploy  
  script:
  - pip install -U -r ./docs/requirements.txt
  - sphinx-build -b html ./docs public
  artifacts:
    paths:
    - public
  only:
  - master
