// Generated by gencpp from file mas514/WebJoystick.msg
// DO NOT EDIT!


#ifndef MAS514_MESSAGE_WEBJOYSTICK_H
#define MAS514_MESSAGE_WEBJOYSTICK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mas514
{
template <class ContainerAllocator>
struct WebJoystick_
{
  typedef WebJoystick_<ContainerAllocator> Type;

  WebJoystick_()
    : x(0)
    , y(0)  {
    }
  WebJoystick_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::mas514::WebJoystick_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mas514::WebJoystick_<ContainerAllocator> const> ConstPtr;

}; // struct WebJoystick_

typedef ::mas514::WebJoystick_<std::allocator<void> > WebJoystick;

typedef boost::shared_ptr< ::mas514::WebJoystick > WebJoystickPtr;
typedef boost::shared_ptr< ::mas514::WebJoystick const> WebJoystickConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mas514::WebJoystick_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mas514::WebJoystick_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mas514::WebJoystick_<ContainerAllocator1> & lhs, const ::mas514::WebJoystick_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mas514::WebJoystick_<ContainerAllocator1> & lhs, const ::mas514::WebJoystick_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mas514

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mas514::WebJoystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mas514::WebJoystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mas514::WebJoystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mas514::WebJoystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mas514::WebJoystick_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mas514::WebJoystick_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mas514::WebJoystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b834ede922a0fff22c43585c533b49f";
  }

  static const char* value(const ::mas514::WebJoystick_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b834ede922a0fffULL;
  static const uint64_t static_value2 = 0x22c43585c533b49fULL;
};

template<class ContainerAllocator>
struct DataType< ::mas514::WebJoystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mas514/WebJoystick";
  }

  static const char* value(const ::mas514::WebJoystick_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mas514::WebJoystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y\n"
;
  }

  static const char* value(const ::mas514::WebJoystick_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mas514::WebJoystick_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WebJoystick_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mas514::WebJoystick_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mas514::WebJoystick_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAS514_MESSAGE_WEBJOYSTICK_H
